Move steps around + add os configuration

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -41,20 +41,47 @@ on:
       out-of-tree-build:
         type: string
         required: false
+      builder-os:
+        type: string
+        required: true
+        default: '["sh-ubuntu"]'
 
 jobs:
   build:
-    runs-on: [sh-ubuntu]
+    strategy:
+      matrix:
+        os: ${{ fromJson(inputs.os) }}
+    runs-on: ${{ matrix.os }}
     steps:
+      - name: Configure builder
+        shell: bash
+        run: |
+            ## Go to workspace given by the runner (this file is generated by the pre-build script)
+            WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
+            echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
+
+            cd $WORKSPACE
+
+            ## Setup github
+            # Git config (needed by CMake ExternalProject)
+            if ! git config --get user.name; then
+                git config --system user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    git config --global user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    git config user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    echo "WARNING: cannot setup git config"
+            fi
+            if ! git config --get user.email; then
+                git config --system user.email '<>' > /dev/null 2>&1 ||
+                    git config --global user.email '<>' > /dev/null 2>&1 ||
+                    git config user.email '<>' > /dev/null 2>&1 ||
+                    echo "WARNING: cannot setup git config"
+            fi
+
+            ##TODO (if required) fix path too long for windows (see main.sh:201)
+
       - name: Clone SOFA and CI
         shell: bash
         run: |
-          ## Go to workspace given by the runner (this file is generated by the pre-build script)
-          WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
-          echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
-
-          cd $WORKSPACE
-
           ## Clone sofa and merge origin master
           echo "Cloning SOFA at commit $GITHUB_WORKFLOW_SHA"
           if [ -d  $WORKSPACE/sofa ]; then
