add BUILDER_OS environment variable

diff --git a/.github/workflows/filter-build.yml b/.github/workflows/filter-build.yml
--- a/.github/workflows/filter-build.yml
+++ b/.github/workflows/filter-build.yml
@@ -33,6 +33,10 @@ on:
         required: true
         default: true
         type: boolean
+      builder_os:
+        type: string
+        required: true
+        default: '["sh-ubuntu_gcc_release"]'
 
   # Nightly build
   schedule:
@@ -75,6 +79,7 @@ jobs:
       PR_OWNER_URL: ${{ steps.export-vars.outputs.PR_OWNER_URL }}
       PR_BRANCH_NAME: ${{ steps.export-vars.outputs.PR_BRANCH_NAME }}
       PR_COMMIT_SHA: ${{ steps.export-vars.outputs.PR_COMMIT_SHA }}
+      BUILDER_OS: ${{ steps.export-vars.outputs.BUILDER_OS }}
       
     steps:
       - name: Default values of environment variables
@@ -91,6 +96,7 @@ jobs:
           echo "PR_OWNER_URL=" >> $GITHUB_ENV              # PR_OWNER_URL: ""
           echo "PR_BRANCH_NAME=" >> $GITHUB_ENV            # PR_BRANCH_NAME: ""
           echo "PR_COMMIT_SHA=HEAD" >> $GITHUB_ENV         # PR_COMMIT_SHA: "HEAD"
+          echo 'BUILDER_OS=["sh-ubuntu_gcc_release"]' >> $GITHUB_ENV            # BUILDER_OS: ["sh-ubuntu_gcc_release"]
           
       - name: Run on dispatch
         if: ${{ github.event_name == 'workflow_dispatch' }}
@@ -102,6 +108,7 @@ jobs:
           PYTHON=${{ github.event.inputs.python_version }}
           PRESET=${{ github.event.inputs.preset }}
           GENERATE_BINARIES=${{ github.event.inputs.generate_binaries }}
+          BUILDER_OS=${{ github.event.inputs.builder_os }}
 
           # Validate branch format (e.g., v25.06)
           if [[ ! "$BRANCH" =~ ^v[0-9]{2}\.[0-9]{2}$ ]]; then
@@ -145,6 +152,13 @@ jobs:
             echo "Error: 'generate_binaries' must be either 'true' or 'false'."
             exit 1
           fi
+
+          # Validate builder_os (must be a list)
+          python3 -c "import ast; x=ast.literal_eval('$BUILDER_OS'); assert isinstance(x, list)" 2>/dev/null
+          if [[ $? -ne 0 ]]; then
+            echo "Error: 'builder_os' must be a list."
+            return 1
+          fi
           
           # Save all information in environment variables
           echo "SOFA_BRANCH_NAME=$BRANCH" >> $GITHUB_ENV
@@ -152,6 +166,7 @@ jobs:
           echo "PRESET=$PRESET" >> $GITHUB_ENV
           echo "PYTHON_VERSION=$PYTHON" >> $GITHUB_ENV
           echo "GENERATE_BINARIES=$GENERATE_BINARIES" >> $GITHUB_ENV
+          echo "BUILDER_OS=$BUILDER_OS" >> $GITHUB_ENV
 
       - name: Set up python
         uses: actions/setup-python@v5
@@ -174,6 +189,7 @@ jobs:
           echo "PRESET=standard" >> $GITHUB_ENV
           echo "WITH_ALL_TESTS=true" >> $GITHUB_ENV
           echo "GENERATE_BINARIES=true" >> $GITHUB_ENV
+          echo 'BUILDER_OS=["sh-ubuntu_gcc_release","sh-windows_vs2022_release","sh-macos_clang_release"]' >> $GITHUB_ENV
 
       - name: Check push on master case
         if: ${{ github.event_name == 'push'}}
@@ -182,6 +198,7 @@ jobs:
           echo "COMMIT_SHA=${{ github.after }}>> $GITHUB_ENV
           echo "WITH_ALL_TESTS=true" >> $GITHUB_ENV
           echo "FORCE_FULL_BUILD=true" >> $GITHUB_ENV
+          echo 'BUILDER_OS=["sh-ubuntu_gcc_release","sh-ubuntu_clang_release","sh-ubuntu_clang_debug","sh-fedora_clang_release","sh-windows_vs2022_release","sh-macos_clang_release"]' >> $GITHUB_ENV
 
       - name: Run when PR is opened
         if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize') }}
@@ -228,6 +245,7 @@ jobs:
           echo "PR_OWNER_URL=${PR_OWNER_URL}" >> $GITHUB_OUTPUT
           echo "PR_BRANCH_NAME=${PR_BRANCH_NAME}" >> $GITHUB_OUTPUT
           echo "PR_COMMIT_SHA=${PR_COMMIT_SHA}" >> $GITHUB_OUTPUT
+          echo "BUILDER_OS=${BUILDER_OS}" >> $GITHUB_OUTPUT
 
 
   # ===============================================================
@@ -250,5 +268,6 @@ jobs:
       pr-owner-url: ${{ needs.set-vars.outputs.PR_OWNER_URL }}
       pr-branch-name: ${{ needs.set-vars.outputs.PR_BRANCH_NAME }}
       pr-commit-sha: ${{ needs.set-vars.outputs.PR_COMMIT_SHA }}
+      builder-os: ${{ needs.set-vars.outputs.BUILDER_OS }}
     secrets:
       personal_access_token: ${{ secrets.GITHUB_TOKEN }}
