Check that SOFA branch name is either master or vXX.XX

diff --git a/.github/workflows/filter-build.yml b/.github/workflows/filter-build.yml
--- a/.github/workflows/filter-build.yml
+++ b/.github/workflows/filter-build.yml
@@ -107,8 +107,9 @@ jobs:
           BUILDER_OS=${{ github.event.inputs.builder_os }}
 
           # Validate branch format (e.g., v25.06)
-          if [[ ! "$BRANCH" =~ ^v[0-9]{2}\.[0-9]{2}$ ]]; then
-            echo "Error: Invalid branch name format: $BRANCH"
+          if [ [ ! "$BRANCH" =~ ^v[0-9]{2}\.[0-9]{2}$ ] && [ "$BRANCH" != "master" ] ]; then
+            echo "Error: Invalid branch name format: $BRANCH."
+            echo "Branch name should be either master or any release branch (e.g., v25.06)"
             exit 1
           fi
           echo "Branch name $BRANCH is valid."
@@ -219,6 +220,13 @@ jobs:
       - name: Export environment variables as outputs
         id: export-vars
         run: |
+          # Validate branch format (e.g., v25.06)
+          if [ [ ! "$SOFA_BRANCH_NAME" =~ ^v[0-9]{2}\.[0-9]{2}$ ] && [ "$SOFA_BRANCH_NAME" != "master" ] ]; then
+            echo "Error: Invalid branch name format: $SOFA_BRANCH_NAME."
+            echo "Branch name should be either master or any release branch (e.g., v25.06)"
+            exit 1
+          fi
+          
           echo "SOFA_BRANCH_NAME=${SOFA_BRANCH_NAME}" >> $GITHUB_OUTPUT
           echo "SOFA_COMMIT_SHA=${SOFA_COMMIT_SHA}" >> $GITHUB_OUTPUT
           echo "PRESET=${PRESET}" >> $GITHUB_OUTPUT
